"""initial schema

Revision ID: 6c3102307f06
Revises: 
Create Date: 2026-08-05 22:16:03.718568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('liked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_item_user_id'), 'library_item', ['user_id'], unique=False)
    op.create_index(op.f('ix_library_item_video_id'), 'library_item', ['video_id'], unique=True)
    op.create_table('playlist',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('youtube_playlist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_user_id'), 'playlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlist_youtube_playlist_id'), 'playlist', ['youtube_playlist_id'], unique=False)
    op.create_table('review_queue_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_item_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'write_pending', 'approved', 'moved', 'rejected', 'stale')", name='ck_review_queue_item_status'),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_item.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_item_library_item_id'), 'review_queue_item', ['library_item_id'], unique=False)
    op.create_index(op.f('ix_review_queue_item_playlist_id'), 'review_queue_item', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_review_queue_item_status'), 'review_queue_item', ['status'], unique=False)
    op.create_index(op.f('ix_review_queue_item_user_id'), 'review_queue_item', ['user_id'], unique=False)
    op.create_table('correction_log_entry',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_queue_item_id', sa.Integer(), nullable=False),
    sa.Column('original_playlist_id', sa.Integer(), nullable=True),
    sa.Column('corrected_playlist_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corrected_playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['original_playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['review_queue_item_id'], ['review_queue_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_log_entry_review_queue_item_id'), 'correction_log_entry', ['review_queue_item_id'], unique=False)
    op.create_index(op.f('ix_correction_log_entry_user_id'), 'correction_log_entry', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # KTD20: correction_log immutability enforced at the DB layer, not left as an
    # ORM convention. SQLite-specific triggers for now; a Postgres cutover (KTD2)
    # will need an equivalent (e.g. a REVOKE UPDATE/DELETE + rule, or a trigger).
    op.execute(
        """
        CREATE TRIGGER correction_log_entry_no_update
        BEFORE UPDATE ON correction_log_entry
        BEGIN
            SELECT RAISE(ABORT, 'correction_log_entry is append-only: updates are not allowed');
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER correction_log_entry_no_delete
        BEFORE DELETE ON correction_log_entry
        BEGIN
            SELECT RAISE(ABORT, 'correction_log_entry is append-only: deletes are not allowed');
        END;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS correction_log_entry_no_delete")
    op.execute("DROP TRIGGER IF EXISTS correction_log_entry_no_update")
    op.drop_index(op.f('ix_correction_log_entry_user_id'), table_name='correction_log_entry')
    op.drop_index(op.f('ix_correction_log_entry_review_queue_item_id'), table_name='correction_log_entry')
    op.drop_table('correction_log_entry')
    op.drop_index(op.f('ix_review_queue_item_user_id'), table_name='review_queue_item')
    op.drop_index(op.f('ix_review_queue_item_status'), table_name='review_queue_item')
    op.drop_index(op.f('ix_review_queue_item_playlist_id'), table_name='review_queue_item')
    op.drop_index(op.f('ix_review_queue_item_library_item_id'), table_name='review_queue_item')
    op.drop_table('review_queue_item')
    op.drop_index(op.f('ix_playlist_youtube_playlist_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_user_id'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_library_item_video_id'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_user_id'), table_name='library_item')
    op.drop_table('library_item')
    op.drop_table('user')
    # ### end Alembic commands ###
