"""structured playlist rule and genre cache

Revision ID: 1c877b46e9c24df89b56e1380a6785e0
Revises: fc554e2ef74b453191e4f2fd33fc1ed3
Create Date: 2026-08-05 22:35:27.253412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1c877b46e9c24df89b56e1380a6785e0'
down_revision: Union[str, None] = 'fc554e2ef74b453191e4f2fd33fc1ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
