"""library item removed_at

Revision ID: d0f6a604b0bb4c0fb7b1afa636cfb033
Revises: 1c877b46e9c24df89b56e1380a6785e0
Create Date: 2026-08-05 22:48:27.719719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'd0f6a604b0bb4c0fb7b1afa636cfb033'
down_revision: Union[str, None] = '1c877b46e9c24df89b56e1380a6785e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_item', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_item', 'removed_at')
    # ### end Alembic commands ###
