"""user onboarding completed at

Revision ID: 5435fa41706147baafb66aadbf0c4faa
Revises: d0f6a604b0bb4c0fb7b1afa636cfb033
Create Date: 2026-08-05 23:39:21.266820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '5435fa41706147baafb66aadbf0c4faa'
down_revision: Union[str, None] = 'd0f6a604b0bb4c0fb7b1afa636cfb033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'onboarding_completed_at')
    # ### end Alembic commands ###
