"""reorganize session matching status

Revision ID: 50bcb671a882
Revises: a581436263e3
Create Date: 2026-08-09 23:17:32.196145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '50bcb671a882'
down_revision: Union[str, None] = 'a581436263e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (this table already has data in
    # any deployed environment) -- SQLModel's Python-level default=... only
    # applies to new objects constructed in Python, not to the ALTER TABLE.
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'matching_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='idle'
            )
        )
        batch_op.add_column(sa.Column('matched_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.drop_column('matched_count')
        batch_op.drop_column('matching_status')

    # ### end Alembic commands ###
