"""user backfill completed at

Revision ID: f8b3e63b587d452f8b2a9b1ce76e2c4b
Revises: 5435fa41706147baafb66aadbf0c4faa
Create Date: 2026-08-05 23:48:36.807480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'f8b3e63b587d452f8b2a9b1ce76e2c4b'
down_revision: Union[str, None] = '5435fa41706147baafb66aadbf0c4faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('backfill_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'backfill_completed_at')
    # ### end Alembic commands ###
