"""reorganize session and playlist proposal

Revision ID: 4deb6a874265
Revises: f8b3e63b587d452f8b2a9b1ce76e2c4b
Create Date: 2026-08-07 17:53:46.568301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '4deb6a874265'
down_revision: Union[str, None] = 'f8b3e63b587d452f8b2a9b1ce76e2c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reorganize_session',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id_snapshot', sa.JSON(), nullable=True),
    sa.Column('clustering_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apply_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apply_last_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reorganize_session_user_id'), ['user_id'], unique=False)

    op.create_table('playlist_proposal',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reorganize_session_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('song_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reorganize_session_id'], ['reorganize_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_proposal_reorganize_session_id'), ['reorganize_session_id'], unique=False)

    with op.batch_alter_table('review_queue_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorganize_session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_review_queue_item_reorganize_session_id'), ['reorganize_session_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_review_queue_item_reorganize_session_id_reorganize_session',
            'reorganize_session',
            ['reorganize_session_id'],
            ['id'],
        )
        batch_op.drop_constraint('ck_review_queue_item_status', type_='check')
        batch_op.create_check_constraint(
            'ck_review_queue_item_status',
            "status IN ('pending', 'write_pending', 'approved', 'moved', 'rejected', 'stale', 'approved_pending_apply')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_queue_item', schema=None) as batch_op:
        batch_op.drop_constraint('ck_review_queue_item_status', type_='check')
        batch_op.create_check_constraint(
            'ck_review_queue_item_status',
            "status IN ('pending', 'write_pending', 'approved', 'moved', 'rejected', 'stale')",
        )
        batch_op.drop_constraint(
            'fk_review_queue_item_reorganize_session_id_reorganize_session', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_review_queue_item_reorganize_session_id'))
        batch_op.drop_column('reorganize_session_id')

    with op.batch_alter_table('playlist_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_proposal_reorganize_session_id'))

    op.drop_table('playlist_proposal')
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reorganize_session_user_id'))

    op.drop_table('reorganize_session')
    # ### end Alembic commands ###
