"""onboarding proposals background

Revision ID: a2d8e4f6c9b1
Revises: f7a1c9d2e5b3
Create Date: 2026-08-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a2d8e4f6c9b1'
down_revision: Union[str, None] = 'f7a1c9d2e5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'onboarding_proposal',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('song_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('onboarding_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_proposal_user_id'), ['user_id'], unique=False)

    # server_default backfills existing rows (this table already has data in
    # any deployed environment) -- SQLModel's Python-level default=... only
    # applies to new objects constructed in Python, not to the ALTER TABLE.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'proposals_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='idle'
            )
        )
        batch_op.add_column(sa.Column('proposals_processed_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('proposals_total_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('proposals_total_count')
        batch_op.drop_column('proposals_processed_count')
        batch_op.drop_column('proposals_status')

    with op.batch_alter_table('onboarding_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_proposal_user_id'))

    op.drop_table('onboarding_proposal')

    # ### end Alembic commands ###
