"""reorganize session enriched_count

Revision ID: a581436263e3
Revises: e4fcbdeef39c
Create Date: 2026-08-09 22:13:22.425297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a581436263e3'
down_revision: Union[str, None] = 'e4fcbdeef39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (this table already has data in
    # any deployed environment) -- SQLModel's Python-level default=0 only
    # applies to new objects constructed in Python, not to the ALTER TABLE.
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enriched_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reorganize_session', schema=None) as batch_op:
        batch_op.drop_column('enriched_count')

    # ### end Alembic commands ###
