"""user ingestion progress

Revision ID: c3f2a9e7b1d4
Revises: 50bcb671a882
Create Date: 2026-08-09 23:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c3f2a9e7b1d4'
down_revision: Union[str, None] = '50bcb671a882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (this table already has data in
    # any deployed environment) -- SQLModel's Python-level default=... only
    # applies to new objects constructed in Python, not to the ALTER TABLE.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'ingestion_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='idle'
            )
        )
        batch_op.add_column(sa.Column('ingestion_processed_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ingestion_total_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ingestion_total_count')
        batch_op.drop_column('ingestion_processed_count')
        batch_op.drop_column('ingestion_status')

    # ### end Alembic commands ###
