"""bpm cache entry

Revision ID: e4fcbdeef39c
Revises: 4deb6a874265
Create Date: 2026-08-09 16:03:19.376518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e4fcbdeef39c'
down_revision: Union[str, None] = '4deb6a874265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bpm_cache_entry',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist', 'title', name='uq_bpm_cache_entry_artist_title')
    )
    with op.batch_alter_table('bpm_cache_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bpm_cache_entry_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_bpm_cache_entry_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpm_cache_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bpm_cache_entry_title'))
        batch_op.drop_index(batch_op.f('ix_bpm_cache_entry_artist'))

    op.drop_table('bpm_cache_entry')
    # ### end Alembic commands ###
