"""playlist source

Revision ID: f7a1c9d2e5b3
Revises: c3f2a9e7b1d4
Create Date: 2026-08-10 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'f7a1c9d2e5b3'
down_revision: Union[str, None] = 'c3f2a9e7b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable, no server_default -- existing rows correctly become NULL
    # ("unknown origin"), which the frontend treats the same as "adopted"
    # (today's only behavior for any pre-existing playlist).
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
